[package]
authors = ["Manu <manu@builder.io>"]
name = "qwik-core"
version = "0.0.1"
edition = "2021"

[[bench]]
name = "transform"
harness = false
html_report = true

[lib]
crate-type = ["rlib"]

[dependencies]
swc_ecmascript = { version = "0.82.0", features = ["parser", "transforms", "module", "typescript", "optimization", "minifier", "react", "utils", "visit", "codegen", "utils"] }
swc_common = { version = "0.14.2", features = ["sourcemap"] }
swc_atoms = "0.2.9"
serde = "1.0.123"
serde_bytes = "0.11.5"
glob = "0.3.0"
simple-error = "0.1.9"
pathdiff = "0.2.1"
relative-path = "1.5.0"

[dev-dependencies]
criterion = "0.3"
insta = "1.8.0"
serde_json = "1.0.68"
