name: Qwik CI

on:
  push:
  pull_request:
  workflow_dispatch:
    name: 'Release'
    description: 'Create a release and publish to NPM.'
    inputs:
      version:
        description: 'Version'
        required: true
      disttag:
        description: 'NPM Dist Tag: latest, next, dev'
        required: true
        default: 'latest'

jobs:
  ############ BUILD PACKAGE ############
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-ubuntu-${{ hashFiles('yarn.lock') }}
          restore-keys: npm-cache-ubuntu-

      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Build Package
        run: node scripts --tsc --build --api --wasm --set-version="${{ github.event.inputs.version }}"

      - name: Upload Package Build Artifacts
        uses: actions/upload-artifact@master
        with:
          name: dist-dev-builder-io-qwik
          path: dist-dev/@builder.io-qwik
          if-no-files-found: error

  ############ BUILD PLATFORM BINDINGS ############
  build-bindings:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              yarn build.napi
              strip -x *.node

          - host: macos-latest
            target: aarch64-apple-darwin
            build: |
              yarn build.napi --target=aarch64-apple-darwin
              strip -x *.node

          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: |
              yarn build.napi --config=napi.config.json

    name: Build ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        working-directory: ./src/napi/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: ${{ matrix.settings.target }}

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
          args: --manifest-path=src/napi/Cargo.toml

      - name: Cache Cargo Registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.settings.target }}-node@16-cargo-registry-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo Index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ matrix.settings.target }}-node@16-cargo-index-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-${{ matrix.settings.target }}-${{ hashFiles('yarn.lock') }}
          restore-keys: npm-cache-${{ matrix.settings.target }}-

      - name: Pull Latest Image
        run: ${{ matrix.settings.docker }}
        env:
          DOCKER_REGISTRY_URL: ghcr.io
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ matrix.settings.docker }}

      - name: Setup Toolchain
        if: ${{ matrix.settings.setup }}
        run: ${{ matrix.settings.setup }}
        shell: bash

      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Build Binding
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Upload Binding Artifact
        uses: actions/upload-artifact@v2
        with:
          name: binding-${{ matrix.settings.target }}
          path: src/napi/*.node

  ############ RELEASE ############
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build-package
      - build-bindings

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2

      - name: Print Package Build Artifacts
        run: ls -R dist-dev-builder-io-qwik

      - name: Print Platform Build Artifacts
        run: ls -R binding-*

      - name: Move Package Artifacts
        run: |
          mkdir dist-dev
          mv dist-dev-builder-io-qwik @builder.io-qwik
          mv @builder.io-qwik dist-dev/@builder.io-qwik

      - name: Move Platform Bindings Artifacts
        run: |
          mv binding-aarch64-apple-darwin/qwik.darwin-arm64.node dist-builder-io-qwik/qwik.darwin-arm64.node
          mv binding-x86_64-apple-darwin/qwik.darwin-x64.node dist-builder-io-qwik/qwik.darwin-x64.node
          mv binding-x86_64-pc-windows-msvc/qwik.win32-x64-msvc.node dist-builder-io-qwik/qwik.win32-x64-msvc.node

      - name: Pack @builder.io/qwik
        run: |
          cd dist-dev/@builder.io-qwik
          mv `npm pack` ../builder.io-qwik.tgz

      - name: Print Dist Directory
        run: ls -R dist-dev

      - name: Upload Qwik Package Artifact
        uses: actions/upload-artifact@master
        with:
          name: builder-io-qwik
          path: dist-dev/builder.io-qwik.tgz

      - name: Cache NPM Dependencies
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-ubuntu-${{ hashFiles('yarn.lock') }}
          restore-keys: npm-cache-ubuntu-

      - name: Install NPM Dependencies
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Publish @builder.io/qwik
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: node scripts --publish --set-version="${{ github.event.inputs.version }}" --set-dist-tag="${{ github.event.inputs.disttag }}" --publish

  ############ LINT ############
  # lint:
  #   name: Lint
  #   if: ${{ github.event_name != 'release' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  # - name: Cache NPM Dependencies
  #   uses: actions/cache@v2
  #   with:
  #     path: node_modules
  #     key: npm-cache-ubuntu-${{ hashFiles('yarn.lock') }}
  #     restore-keys: npm-cache-ubuntu-

  #     - name: Install NPM Dependencies
  #       run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

  #     - name: Prettier Check
  #       run: yarn prettier-check

  #     - name: Lint Check
  #       run: yarn lint

  ############ UNIT TEST ############
  # unit-tests:
  #   name: Unit Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10.x
  #         registry-url: https://registry.npmjs.org/

  #     - name: Checkout
  #       uses: actions/checkout@v2

  # - name: Cache NPM Dependencies
  #   uses: actions/cache@v2
  #   with:
  #     path: node_modules
  #     key: npm-cache-ubuntu-${{ hashFiles('yarn.lock') }}
  #     restore-keys: npm-cache-ubuntu-

  #     - name: Install NPM Dependencies
  #       run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

  #     - name: Unit Tests
  #       run: |
  #         yarn build
  #         yarn test.unit

  ############ E2E TEST ############
  # e2e-tests:
  #   name: E2E Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10.x
  #         registry-url: https://registry.npmjs.org/

  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: E2E Tests
  #       uses: cypress-io/github-action@v2
  #       with:
  #         install-command: yarn --frozen-lockfile --ignore-engines
  #         start: yarn integration.server.prod
  #         wait-on: 'http://localhost:8081'
  #         wait-on-timeout: 120
  #         browser: chrome
  #         record: true
  #         group: 'Qwik E2E Test Group'
  #         spec: cypress/integration/*
  #         config-file: cypress/cypress.json
  #         config: defaultCommandTimeout=10000
  #       env:
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Upload Videos Artifacts
  #       uses: actions/upload-artifact@v1
  #       if: always()
  #       with:
  #         name: Cypress Videos
  #         path: cypress/videos
