name: Qwik CI

on:
  push:
  workflow_dispatch:
    name: 'Release'
    description: 'Commit version update to git, publish to NPM, and create a Github release.'
    inputs:
      version:
        description: 'Version'
        required: true
      disttag:
        description: 'NPM Dist Tag: latest, next, dev'
        required: true
        default: 'latest'

env:
  # Disable incremental build, speeds up CI
  CARGO_INCREMENTAL: 0

jobs:
  ############ RELEASE ############
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-ubuntu-${{ hashFiles('yarn.lock') }}
          restore-keys: npm-cache-ubuntu-

      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Publish @builder.io/qwik
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: node scripts --set-version="0.0.1" --set-dist-tag="dev" --publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
